{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.dagger.hilt.android",
    "module": "com.google.dagger.hilt.android.gradle.plugin",
    "version": "2.51.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "hilt-android-gradle-plugin",
          "version": {
            "requires": "2.51.1"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.dagger",
          "module": "hilt-android-gradle-plugin",
          "version": {
            "requires": "2.51.1"
          }
        }
      ]
    }
  ]
}
