{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.dagger",
    "module": "hilt-android-gradle-plugin",
    "version": "2.51.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.status": "release",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hilt-android-gradle-plugin-2.51.1.jar",
          "url": "hilt-android-gradle-plugin-2.51.1.jar",
          "size": 246233,
          "sha512": "78aaa1922e93151267ac11ffe6caee10a482578b0da9120eabcaf160c994c3865239dbdbe6db5172f0f2dd2fbd4bdd3f34edceab5807ca5c7368e42c3085168a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.status": "release",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-android-gradle-plugin-2.51.1.jar",
          "url": "hilt-android-gradle-plugin-2.51.1.jar",
          "size": 246233,
          "sha512": "78aaa1922e93151267ac11ffe6caee10a482578b0da9120eabcaf160c994c3865239dbdbe6db5172f0f2dd2fbd4bdd3f34edceab5807ca5c7368e42c3085168a"
        }
      ]
    }
  ]
}
