name: Android Debug Build

on:
  push:
  pull_request:

concurrency:
  group: android-debug-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - name: Build debug artefact
        run: ./gradlew --no-daemon clean lint test :app:assembleDebug
      - name: Upload debug artefact
        uses: actions/upload-artifact@v4
        with:
          name: letsdoit-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload lint reports
        if: ${{ hashFiles('app/build/reports/lint-results*.html') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: app/build/reports/lint-results*.html
      - name: Upload unit test reports
        if: ${{ hashFiles('app/build/reports/tests/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: app/build/reports/tests
      - name: Share artefact link
        run: echo "[Download the debug artefact](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts)" >> $GITHUB_STEP_SUMMARY
