name: Android Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Assert no Kotlin plugin versions in subprojects
        run: .github/scripts/assert-no-plugin-versions.sh

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Prepare environment
        run: echo "APK_PATH=app/build/outputs/apk/release/app-release-unsigned.apk" >> $GITHUB_ENV

      - name: Build release
        run: ./gradlew --no-daemon :app:assembleRelease -Dkotlin.compiler.execution.strategy=in-process

      - name: Determine signing
        run: |
          if [ -n "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ] && [ -n "${{ secrets.RELEASE_STORE_PASSWORD }}" ] && [ -n "${{ secrets.RELEASE_KEY_ALIAS }}" ] && [ -n "${{ secrets.RELEASE_KEY_PASSWORD }}" ]; then
            echo "SHOULD_SIGN=true" >> $GITHUB_ENV
          else
            echo "SHOULD_SIGN=false" >> $GITHUB_ENV
          fi

      - name: Sign release APK
        if: env.SHOULD_SIGN == 'true'
        env:
          KEYSTORE: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          echo "$KEYSTORE" | base64 --decode > release.keystore
          UNSIGNED_APK="app/build/outputs/apk/release/app-release-unsigned.apk"
          ALIGNED_APK="app/build/outputs/apk/release/app-release-aligned.apk"
          SIGNED_APK="app/build/outputs/apk/release/app-release.apk"
          BUILD_TOOLS=$(ls $ANDROID_HOME/build-tools | sort -V | tail -n 1)
          $ANDROID_HOME/build-tools/$BUILD_TOOLS/zipalign -f -v 4 "$UNSIGNED_APK" "$ALIGNED_APK"
          $ANDROID_HOME/build-tools/$BUILD_TOOLS/apksigner sign --ks release.keystore --ks-key-alias "$KEY_ALIAS" --ks-pass env:STORE_PASSWORD --key-pass env:KEY_PASSWORD --out "$SIGNED_APK" "$ALIGNED_APK"
          echo "APK_PATH=$SIGNED_APK" >> $GITHUB_ENV

      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.APK_PATH }}
